services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
